language: shell
sudo: required
install:
- sudo ./setup.sh
script:
- bash -c 'shopt -s globstar nullglob; shellcheck **/*.sh'
- bpkg update
- bpkg list
- bpkg show bpkg/github
- sudo bpkg install bpkg/github -g
- bpkg install bpkg/term
