on:
  - push
  - pull_request

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pipeline-components/shellcheck@v0.6.1
        with:
          options: -f gcc -x lib/utils/utils.sh
