---
on:
  - push
  - pull_request

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Shellcheck
        run: |
          shellcheck --version
          find . -type f -name "*.sh" -exec shellcheck --format=gcc --external-sources --exclude=SC2230 "{}" "+"
