---
on:
  - push
  - pull_request

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file:
          - bpkg.sh
          - lib/getdeps/getdeps.sh
          - lib/init/init.sh
          - lib/install/install.sh
          - lib/json/JSON.sh
          - lib/list/list.sh
          - lib/package/package.sh
          - lib/run/run.sh
          - lib/show/show.sh
          - lib/source/source.sh
          - lib/suggest/suggest.sh
          - lib/term/term.sh
          - lib/update/update.sh
          - lib/utils/utils.sh
          - setup.sh
    steps:
      - uses: actions/checkout@v3
      - uses: pipeline-components/shellcheck@v0.6.1
        with:
          directory: ${{ matrix.file }}
          options: -f gcc -x
