name: versions
on:
  - pull_request
  - push

jobs:
  v0-0-2:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Setup For 0.0.2
        run: |
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.0.2/setup.sh | bash
          bpkg --version | grep 0.0.2

