name: versions
on:
  - pull_request
  - push

jobs:
  verify-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Setup For Tags
        run: |
          echo "Verify 0.0.2:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.0.2/setup.sh | bash
          bpkg --version | grep 0.0.2

          echo "Verify 0.0.3:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.0.3/setup.sh | bash
          bpkg --version | grep 0.0.3

          echo "Verify 0.0.4:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.0.4/setup.sh | bash
          bpkg --version | grep 0.0.4

          echo "Verify 0.0.5:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.0.5/setup.sh | bash
          bpkg --version | grep 0.0.5

          echo "Verify 0.0.6:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.0.6/setup.sh | bash
          bpkg --version | grep 0.0.6

          echo "Verify 0.0.7:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.0.7/setup.sh | bash
          bpkg --version | grep 0.0.7

          echo "Verify 0.0.8:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.0.8/setup.sh | bash
          bpkg --version | grep 0.0.8

          echo "Verify 0.0.9:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.0.9/setup.sh | bash
          bpkg --version | grep 0.0.9

          echo "Verify 0.1.0:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.1.0/setup.sh | bash
          bpkg --version | grep 0.1.0

          echo "Verify 0.2.0:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.2.0/setup.sh | bash
          bpkg --version | grep 0.2.0

          echo "Verify 0.2.1:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.2.1/setup.sh | bash
          bpkg --version | grep 0.2.1

          echo "Verify 0.2.2:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.2.2/setup.sh | bash
          bpkg --version | grep 0.2.2

          echo "Verify 0.2.3:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.2.3/setup.sh | bash
          bpkg --version | grep 0.2.3

          echo "Verify 0.2.4:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.2.4/setup.sh | bash
          bpkg --version | grep 0.2.4

          echo "Verify 0.2.5:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.2.5/setup.sh | bash
          bpkg --version | grep 0.2.5

          echo "Verify 0.2.6:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.2.6/setup.sh | bash
          bpkg --version | grep 0.2.6

          echo "Verify 0.2.7:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.2.7/setup.sh | bash
          bpkg --version | grep 0.2.7

          echo "Verify 0.2.8:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.2.8/setup.sh | bash
          bpkg --version | grep 0.2.8

          echo "Verify 0.2.9:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.2.9/setup.sh | bash
          bpkg --version | grep 0.2.9

          echo "Verify 0.3.0:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.3.0/setup.sh | bash
          bpkg --version | grep 0.3.0

          echo "Verify 0.3.1:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.3.1/setup.sh | bash
          bpkg --version | grep 0.3.1

          echo "Verify 0.3.2:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/0.3.2/setup.sh | bash
          bpkg --version | grep 0.3.2

          echo "Verify 1.0.0:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.0/setup.sh | bash
          bpkg --version | grep 1.0.0

          echo "Verify 1.0.1:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.1/setup.sh | bash
          bpkg --version | grep 1.0.1

          echo "Verify 1.0.10:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.10/setup.sh | bash
          bpkg --version | grep 1.0.10

          echo "Verify 1.0.11:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.11/setup.sh | bash
          bpkg --version | grep 1.0.11

          echo "Verify 1.0.12:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.12/setup.sh | bash
          bpkg --version | grep 1.0.12

          echo "Verify 1.0.13:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.13/setup.sh | bash
          bpkg --version | grep 1.0.13

          echo "Verify 1.0.14:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.14/setup.sh | bash
          bpkg --version | grep 1.0.14

          echo "Verify 1.0.15:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.15/setup.sh | bash
          bpkg --version | grep 1.0.15

          echo "Verify 1.0.16:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.16/setup.sh | bash
          bpkg --version | grep 1.0.16

          echo "Verify 1.0.17:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.17/setup.sh | bash
          bpkg --version | grep 1.0.17

          echo "Verify 1.0.18:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.18/setup.sh | bash
          bpkg --version | grep 1.0.18

          echo "Verify 1.0.19:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.19/setup.sh | bash
          bpkg --version | grep 1.0.19

          echo "Verify 1.0.2:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.2/setup.sh | bash
          bpkg --version | grep 1.0.2

          echo "Verify 1.0.20:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.20/setup.sh | bash
          bpkg --version | grep 1.0.20

          echo "Verify 1.0.21:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.21/setup.sh | bash
          bpkg --version | grep 1.0.21

          echo "Verify 1.0.22:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.22/setup.sh | bash
          bpkg --version | grep 1.0.22

          echo "Verify 1.0.23:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.23/setup.sh | bash
          bpkg --version | grep 1.0.23

          echo "Verify 1.0.24:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.24/setup.sh | bash
          bpkg --version | grep 1.0.24

          echo "Verify 1.0.25:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.25/setup.sh | bash
          bpkg --version | grep 1.0.25

          echo "Verify 1.0.3:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.3/setup.sh | bash
          bpkg --version | grep 1.0.3

          echo "Verify 1.0.4:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.4/setup.sh | bash
          bpkg --version | grep 1.0.4

          echo "Verify 1.0.5:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.5/setup.sh | bash
          bpkg --version | grep 1.0.5

          echo "Verify 1.0.6:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.6/setup.sh | bash
          bpkg --version | grep 1.0.6

          echo "Verify 1.0.7:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.7/setup.sh | bash
          bpkg --version | grep 1.0.7

          echo "Verify 1.0.8:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.8/setup.sh | bash
          bpkg --version | grep 1.0.8

          echo "Verify 1.0.9:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.0.9/setup.sh | bash
          bpkg --version | grep 1.0.9

          echo "Verify 1.1.0:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.1.0/setup.sh | bash
          bpkg --version | grep 1.1.0

          echo "Verify 1.1.1:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.1.1/setup.sh | bash
          bpkg --version | grep 1.1.1

          echo "Verify 1.1.2:"
          curl https://raw.githubusercontent.com/bpkg/bpkg/1.1.2/setup.sh | bash
          bpkg --version | grep 1.1.2

